# Generated by Django 3.2.3 on 2021-05-30 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderdetail_cuantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='cuantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='orders.order'),
        ),
    ]
